console.log('✅ Enhanced database with comprehensive Jharkhand data:');
console.log('');
console.log('🏨 Hotels Added:');
console.log('  1. Jharkhand Tourism Lodge Ranchi - Capital city accommodation');
console.log('  2. Netarhat Hill Resort - Hill station with valley views');
console.log('  3. Dalma Wildlife Eco Lodge - Near wildlife sanctuary');
console.log('  4. Deoghar Pilgrimage Hotel - Near Baidyanath Temple');
console.log('  5. Jamshedpur Business Hotel - Steel city corporate facilities');
console.log('  6. Betla Forest Lodge - Inside Betla National Park');
console.log('  7. Hazaribagh Lake View Resort - Lakeside with water sports');
console.log('  8. Dhanbad Heritage Hotel - Coal mining history theme');
console.log('  9. Bokaro Spa Resort - Wellness and spa treatments');
console.log('  10. Giridih Rock Garden Hotel - Rock formations and springs');
console.log('');
console.log('✈️ Flight Routes Added:');
console.log('  TO RANCHI (IXR):');
console.log('    • Delhi → Ranchi (Multiple daily flights)');
console.log('    • Mumbai → Ranchi (Morning & evening options)');
console.log('    • Kolkata → Ranchi (Short 1h 10m flights)');
console.log('    • Bangalore → Ranchi (Premium Vistara service)');
console.log('    • Chennai → Ranchi (IndiGo connectivity)');
console.log('    • Pune → Ranchi (SpiceJet routes)');
console.log('    • Hyderabad → Ranchi (Air India Express)');
console.log('');
console.log('  TO DEOGHAR (DGH):');
console.log('    • Delhi → Deoghar (Morning & evening flights)');
console.log('    • Kolkata → Deoghar (Quick 1h 15m connections)');
console.log('    • Mumbai → Deoghar (SpiceJet service)');
console.log('    • Chennai → Deoghar (Vistara premium)');
console.log('    • Bangalore → Deoghar (IndiGo connectivity)');
console.log('    • Ahmedabad → Deoghar (Air India Express)');
console.log('');
console.log('  RETURN FLIGHTS:');
console.log('    • Ranchi/Deoghar → All major cities with convenient timings');
console.log('');
console.log('📊 Database Statistics:');
console.log('  • 10 Hotels across major Jharkhand destinations');
console.log('  • 13 Room types with different amenities');
console.log('  • 23 Flight routes covering both airports');
console.log('  • Comprehensive coverage of Jharkhand tourism');
console.log('');
console.log('🎯 Ready for Booking:');
console.log('  • Visit /book-hotels for hotel reservations');
console.log('  • Visit /book-flights for flight bookings');
console.log('  • All bookings integrated with Razorpay payments');
console.log('  • Real-time availability and instant confirmation');
console.log('');
console.log('🚀 Your Jharkhand Tourism booking system is ready!');
